// Copyright 2022 Jeff Kim <hiking90@gmail.com>
// SPDX-License-Identifier: Apache-2.0

/*
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//! This module lets you use the Tokio `spawn_blocking` pool with AIDL in async
//! Rust code (enabled by the default `tokio` feature).
//!
//! It works by defining a type [`Tokio`], which you use as the generic
//! parameter `P` of the `IFooAsync<P>` trait generated by the AIDL compiler.
//! Obtain an async proxy either with the crate-root [`get_interface_async`] helper,
//! or by upgrading a sync handle with [`Strong::into_async`]:
//!
//! ```text
//! use rsbinder::Tokio;
//!
//! // Look up a service and cast straight to its async interface.
//! let svc = rsbinder::get_interface_async::<dyn SomeAsyncInterface<Tokio>>("name").await?;
//!
//! // Or upgrade an existing sync Strong handle:
//! let svc_async = sync_handle.into_async::<Tokio>();
//! ```
//!
//! [`Tokio`]: crate::Tokio
//! [`get_interface_async`]: crate::get_interface_async
//! [`Strong::into_async`]: crate::Strong::into_async

use crate::{hub, BinderAsyncPool, BinderAsyncRuntime, BoxFuture, FromIBinder, StatusCode, Strong};
use std::future::Future;

/// Retrieve an existing service for a particular interface — one
/// `getService` wire call, which does not block (see
/// [`crate::hub::try_get_interface`]). For an event-driven wait use
/// [`crate::hub::wait_for_interface`]; for a lookup that will not start an
/// unregistered lazy service, [`crate::hub::check_interface`].
///
/// The `_async` suffix is what tells the two apart at the crate root: the
/// synchronous lookups live in [`crate::hub`], and only this one has to be
/// awaited. It matches [`crate::connect_async`], the facade entry point.
pub async fn get_interface_async<T: FromIBinder + ?Sized + 'static>(
    name: &str,
) -> Result<Strong<T>, StatusCode> {
    fn lookup<T: FromIBinder + ?Sized + 'static>(name: &str) -> Result<Strong<T>, StatusCode> {
        hub::try_get_interface::<T>(name)?.ok_or(StatusCode::NameNotFound)
    }

    if crate::is_handling_transaction() {
        // See comment in the BinderAsyncPool impl.
        return lookup::<T>(name);
    }

    let name = name.to_string();
    let res = tokio::task::spawn_blocking(move || lookup::<T>(&name)).await;

    // The `is_panic` branch is not actually reachable in Android as we compile
    // with `panic = abort`.
    match res {
        Ok(Ok(service)) => Ok(service),
        Ok(Err(err)) => Err(err),
        Err(e) if e.is_panic() => std::panic::resume_unwind(e.into_panic()),
        Err(e) if e.is_cancelled() => Err(StatusCode::FailedTransaction),
        Err(_) => Err(StatusCode::Unknown),
    }
}

/// Use the Tokio `spawn_blocking` pool with AIDL.
pub enum Tokio {}

impl BinderAsyncPool for Tokio {
    fn spawn<'a, F1, F2, Fut, A, B, E>(spawn_me: F1, after_spawn: F2) -> BoxFuture<'a, Result<B, E>>
    where
        F1: FnOnce() -> A,
        F2: FnOnce(A) -> Fut,
        Fut: Future<Output = Result<B, E>>,
        F1: Send + 'static,
        F2: Send + 'a,
        Fut: Send + 'a,
        A: Send + 'static,
        B: Send + 'a,
        E: From<crate::StatusCode>,
    {
        // RPC too: a nested call must stay on this thread or it loses the thread-local `DRIVING` pin and deadlocks.
        if crate::is_handling_transaction() {
            // We are currently on the thread pool for a binder server, so we should execute the
            // transaction on the current thread so that the binder kernel driver is able to apply
            // its deadlock prevention strategy to the sub-call.
            //
            // This shouldn't cause issues with blocking the thread as only one task will run in a
            // call to `block_on`, so there aren't other tasks to block.
            let result = spawn_me();
            Box::pin(after_spawn(result))
        } else {
            let handle = tokio::task::spawn_blocking(spawn_me);
            Box::pin(async move {
                // The `is_panic` branch is not actually reachable in Android as we compile
                // with `panic = abort`.
                match handle.await {
                    Ok(res) => after_spawn(res).await,
                    Err(e) if e.is_panic() => std::panic::resume_unwind(e.into_panic()),
                    Err(e) if e.is_cancelled() => Err(StatusCode::FailedTransaction.into()),
                    Err(_) => Err(StatusCode::Unknown.into()),
                }
            })
        }
    }
}

/// Wrapper around a Tokio [`Handle`], for providing a runtime to a binder
/// server.
///
/// An async server implementation is driven by [`BinderAsyncRuntime::block_on`]
/// on whatever thread delivered the transaction — a kernel binder looper, or an
/// RPC session thread. Those threads are outside the runtime, which is the case
/// `Handle::block_on` is built for.
///
/// The same `block_on` is also reached from a *synchronous* handle to a local
/// async service: `Bn*::new_async_binder` returns `Strong<dyn IFoo>`, whose
/// generated wrapper implements each sync method as `block_on(inner.method())`.
/// Calling that handle from a task on a multi-threaded runtime would otherwise
/// panic with "Cannot start a runtime from within a runtime", so this impl
/// releases the worker's core with [`tokio::task::block_in_place`] first.
///
/// Two independent things then decide what the call does, and reading them as
/// one list is how the failures get misattributed. **Where the call is made
/// from** decides whether it runs at all. **Which runtime the handle points at**
/// decides whether the future can finish. Either answer holds whatever the other
/// one is.
///
/// # Panics
///
/// Where the call is made from. These two panic whatever the handle points at:
///
/// - **A current-thread runtime's own thread** — "Cannot start a runtime from
///   within a runtime". The flavor is not `MultiThread`, so no core is released,
///   and the thread is already inside `Runtime::block_on`.
/// - **Inside a [`LocalSet`]** — "can call blocking only when running on the
///   multi-threaded runtime". The surrounding runtime *is* multi-threaded, so
///   the core release is attempted, and `block_in_place` refuses to run in a
///   `LocalSet`.
///
/// Every other position runs: a thread outside any runtime (a binder looper, an
/// RPC session thread), a multi-threaded worker, a `Runtime::block_on` body, and
/// either flavor's `spawn_blocking` pool.
///
/// # Stalls
///
/// Which runtime the handle points at. This decides completion whatever the
/// caller:
///
/// - A **multi-threaded** runtime drives the future on its own workers.
/// - A **current-thread** runtime is driven only while some thread sits inside
///   `Runtime::block_on` on it. `Handle::block_on` polls the future but does not
///   run that runtime's timer and IO drivers, so with nobody parked there a
///   handler that awaits a `sleep` or IO never completes and the call never
///   returns.
///
/// # Cost
///
/// A call from a **worker** thread releases that worker's core for the duration
/// and offers it to the `spawn_blocking` pool. From every other position nothing
/// is released and the call runs inline. When the pool has no free thread the
/// core is not picked up: the call still completes, but a runtime with a
/// *single* worker runs nothing else until it returns. A second worker, or a
/// pool with room, removes that.
///
/// So on a path that calls a local async service repeatedly, convert the handle
/// once with [`Strong::into_async`] and await it instead — that route dispatches
/// to the async service directly and never enters `block_on`.
///
/// [`Handle`]: tokio::runtime::Handle
/// [`LocalSet`]: tokio::task::LocalSet
/// [`Strong::into_async`]: crate::Strong::into_async
pub struct TokioRuntime<R>(pub R);

impl BinderAsyncRuntime for TokioRuntime<tokio::runtime::Handle> {
    fn block_on<F: Future>(&self, future: F) -> F::Output {
        match tokio::runtime::Handle::try_current() {
            // On a multi-threaded runtime — a worker or one of its blocking
            // threads. Give the core up so another thread keeps the scheduler
            // running; on a blocking thread this is a plain inline call.
            Ok(handle) if handle.runtime_flavor() == tokio::runtime::RuntimeFlavor::MultiThread => {
                tokio::task::block_in_place(|| self.0.block_on(future))
            }
            // Outside any runtime (a binder looper, an RPC session thread), or
            // on a current-thread runtime's blocking pool — where `block_on` is
            // allowed, so the flavor must not be turned into a panic here.
            _ => self.0.block_on(future),
        }
    }
}
